/*
Mullvad App API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mullvad_api

import (
	"encoding/json"
)

// checks if the V1WwwAuthTokenPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1WwwAuthTokenPost200Response{}

// V1WwwAuthTokenPost200Response struct for V1WwwAuthTokenPost200Response
type V1WwwAuthTokenPost200Response struct {
	AuthToken *string `json:"auth_token,omitempty"`
}

// NewV1WwwAuthTokenPost200Response instantiates a new V1WwwAuthTokenPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1WwwAuthTokenPost200Response() *V1WwwAuthTokenPost200Response {
	this := V1WwwAuthTokenPost200Response{}
	return &this
}

// NewV1WwwAuthTokenPost200ResponseWithDefaults instantiates a new V1WwwAuthTokenPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1WwwAuthTokenPost200ResponseWithDefaults() *V1WwwAuthTokenPost200Response {
	this := V1WwwAuthTokenPost200Response{}
	return &this
}

// GetAuthToken returns the AuthToken field value if set, zero value otherwise.
func (o *V1WwwAuthTokenPost200Response) GetAuthToken() string {
	if o == nil || IsNil(o.AuthToken) {
		var ret string
		return ret
	}
	return *o.AuthToken
}

// GetAuthTokenOk returns a tuple with the AuthToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1WwwAuthTokenPost200Response) GetAuthTokenOk() (*string, bool) {
	if o == nil || IsNil(o.AuthToken) {
		return nil, false
	}
	return o.AuthToken, true
}

// HasAuthToken returns a boolean if a field has been set.
func (o *V1WwwAuthTokenPost200Response) HasAuthToken() bool {
	if o != nil && !IsNil(o.AuthToken) {
		return true
	}

	return false
}

// SetAuthToken gets a reference to the given string and assigns it to the AuthToken field.
func (o *V1WwwAuthTokenPost200Response) SetAuthToken(v string) {
	o.AuthToken = &v
}

func (o V1WwwAuthTokenPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1WwwAuthTokenPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthToken) {
		toSerialize["auth_token"] = o.AuthToken
	}
	return toSerialize, nil
}

type NullableV1WwwAuthTokenPost200Response struct {
	value *V1WwwAuthTokenPost200Response
	isSet bool
}

func (v NullableV1WwwAuthTokenPost200Response) Get() *V1WwwAuthTokenPost200Response {
	return v.value
}

func (v *NullableV1WwwAuthTokenPost200Response) Set(val *V1WwwAuthTokenPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1WwwAuthTokenPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1WwwAuthTokenPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1WwwAuthTokenPost200Response(val *V1WwwAuthTokenPost200Response) *NullableV1WwwAuthTokenPost200Response {
	return &NullableV1WwwAuthTokenPost200Response{value: val, isSet: true}
}

func (v NullableV1WwwAuthTokenPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1WwwAuthTokenPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


