/*
Mullvad App API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mullvad_api

import (
	"encoding/json"
)

// checks if the V1RelaysGet200ResponseBridge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1RelaysGet200ResponseBridge{}

// V1RelaysGet200ResponseBridge struct for V1RelaysGet200ResponseBridge
type V1RelaysGet200ResponseBridge struct {
	// List of connection specs for Shadowsocks ports
	Shadowsocks []V1RelaysGet200ResponseBridgeShadowsocksInner `json:"shadowsocks,omitempty"`
	Relays []BridgeRelay `json:"relays,omitempty"`
}

// NewV1RelaysGet200ResponseBridge instantiates a new V1RelaysGet200ResponseBridge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1RelaysGet200ResponseBridge() *V1RelaysGet200ResponseBridge {
	this := V1RelaysGet200ResponseBridge{}
	return &this
}

// NewV1RelaysGet200ResponseBridgeWithDefaults instantiates a new V1RelaysGet200ResponseBridge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1RelaysGet200ResponseBridgeWithDefaults() *V1RelaysGet200ResponseBridge {
	this := V1RelaysGet200ResponseBridge{}
	return &this
}

// GetShadowsocks returns the Shadowsocks field value if set, zero value otherwise.
func (o *V1RelaysGet200ResponseBridge) GetShadowsocks() []V1RelaysGet200ResponseBridgeShadowsocksInner {
	if o == nil || IsNil(o.Shadowsocks) {
		var ret []V1RelaysGet200ResponseBridgeShadowsocksInner
		return ret
	}
	return o.Shadowsocks
}

// GetShadowsocksOk returns a tuple with the Shadowsocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RelaysGet200ResponseBridge) GetShadowsocksOk() ([]V1RelaysGet200ResponseBridgeShadowsocksInner, bool) {
	if o == nil || IsNil(o.Shadowsocks) {
		return nil, false
	}
	return o.Shadowsocks, true
}

// HasShadowsocks returns a boolean if a field has been set.
func (o *V1RelaysGet200ResponseBridge) HasShadowsocks() bool {
	if o != nil && !IsNil(o.Shadowsocks) {
		return true
	}

	return false
}

// SetShadowsocks gets a reference to the given []V1RelaysGet200ResponseBridgeShadowsocksInner and assigns it to the Shadowsocks field.
func (o *V1RelaysGet200ResponseBridge) SetShadowsocks(v []V1RelaysGet200ResponseBridgeShadowsocksInner) {
	o.Shadowsocks = v
}

// GetRelays returns the Relays field value if set, zero value otherwise.
func (o *V1RelaysGet200ResponseBridge) GetRelays() []BridgeRelay {
	if o == nil || IsNil(o.Relays) {
		var ret []BridgeRelay
		return ret
	}
	return o.Relays
}

// GetRelaysOk returns a tuple with the Relays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RelaysGet200ResponseBridge) GetRelaysOk() ([]BridgeRelay, bool) {
	if o == nil || IsNil(o.Relays) {
		return nil, false
	}
	return o.Relays, true
}

// HasRelays returns a boolean if a field has been set.
func (o *V1RelaysGet200ResponseBridge) HasRelays() bool {
	if o != nil && !IsNil(o.Relays) {
		return true
	}

	return false
}

// SetRelays gets a reference to the given []BridgeRelay and assigns it to the Relays field.
func (o *V1RelaysGet200ResponseBridge) SetRelays(v []BridgeRelay) {
	o.Relays = v
}

func (o V1RelaysGet200ResponseBridge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1RelaysGet200ResponseBridge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Shadowsocks) {
		toSerialize["shadowsocks"] = o.Shadowsocks
	}
	if !IsNil(o.Relays) {
		toSerialize["relays"] = o.Relays
	}
	return toSerialize, nil
}

type NullableV1RelaysGet200ResponseBridge struct {
	value *V1RelaysGet200ResponseBridge
	isSet bool
}

func (v NullableV1RelaysGet200ResponseBridge) Get() *V1RelaysGet200ResponseBridge {
	return v.value
}

func (v *NullableV1RelaysGet200ResponseBridge) Set(val *V1RelaysGet200ResponseBridge) {
	v.value = val
	v.isSet = true
}

func (v NullableV1RelaysGet200ResponseBridge) IsSet() bool {
	return v.isSet
}

func (v *NullableV1RelaysGet200ResponseBridge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1RelaysGet200ResponseBridge(val *V1RelaysGet200ResponseBridge) *NullableV1RelaysGet200ResponseBridge {
	return &NullableV1RelaysGet200ResponseBridge{value: val, isSet: true}
}

func (v NullableV1RelaysGet200ResponseBridge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1RelaysGet200ResponseBridge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


