/*
Mullvad App API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mullvad_api

import (
	"encoding/json"
)

// checks if the OpenVpnRelay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenVpnRelay{}

// OpenVpnRelay struct for OpenVpnRelay
type OpenVpnRelay struct {
	Hostname *string `json:"hostname,omitempty"`
	Location *string `json:"location,omitempty"`
	Active *bool `json:"active,omitempty"`
	Owned *bool `json:"owned,omitempty"`
	Provider *string `json:"provider,omitempty"`
	Ipv4AddrIn *string `json:"ipv4_addr_in,omitempty"`
	IncludeInCountry *bool `json:"include_in_country,omitempty"`
	Weight *int32 `json:"weight,omitempty"`
}

// NewOpenVpnRelay instantiates a new OpenVpnRelay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenVpnRelay() *OpenVpnRelay {
	this := OpenVpnRelay{}
	return &this
}

// NewOpenVpnRelayWithDefaults instantiates a new OpenVpnRelay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenVpnRelayWithDefaults() *OpenVpnRelay {
	this := OpenVpnRelay{}
	return &this
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *OpenVpnRelay) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenVpnRelay) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *OpenVpnRelay) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *OpenVpnRelay) SetHostname(v string) {
	o.Hostname = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *OpenVpnRelay) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenVpnRelay) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *OpenVpnRelay) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *OpenVpnRelay) SetLocation(v string) {
	o.Location = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *OpenVpnRelay) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenVpnRelay) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *OpenVpnRelay) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *OpenVpnRelay) SetActive(v bool) {
	o.Active = &v
}

// GetOwned returns the Owned field value if set, zero value otherwise.
func (o *OpenVpnRelay) GetOwned() bool {
	if o == nil || IsNil(o.Owned) {
		var ret bool
		return ret
	}
	return *o.Owned
}

// GetOwnedOk returns a tuple with the Owned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenVpnRelay) GetOwnedOk() (*bool, bool) {
	if o == nil || IsNil(o.Owned) {
		return nil, false
	}
	return o.Owned, true
}

// HasOwned returns a boolean if a field has been set.
func (o *OpenVpnRelay) HasOwned() bool {
	if o != nil && !IsNil(o.Owned) {
		return true
	}

	return false
}

// SetOwned gets a reference to the given bool and assigns it to the Owned field.
func (o *OpenVpnRelay) SetOwned(v bool) {
	o.Owned = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *OpenVpnRelay) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenVpnRelay) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *OpenVpnRelay) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *OpenVpnRelay) SetProvider(v string) {
	o.Provider = &v
}

// GetIpv4AddrIn returns the Ipv4AddrIn field value if set, zero value otherwise.
func (o *OpenVpnRelay) GetIpv4AddrIn() string {
	if o == nil || IsNil(o.Ipv4AddrIn) {
		var ret string
		return ret
	}
	return *o.Ipv4AddrIn
}

// GetIpv4AddrInOk returns a tuple with the Ipv4AddrIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenVpnRelay) GetIpv4AddrInOk() (*string, bool) {
	if o == nil || IsNil(o.Ipv4AddrIn) {
		return nil, false
	}
	return o.Ipv4AddrIn, true
}

// HasIpv4AddrIn returns a boolean if a field has been set.
func (o *OpenVpnRelay) HasIpv4AddrIn() bool {
	if o != nil && !IsNil(o.Ipv4AddrIn) {
		return true
	}

	return false
}

// SetIpv4AddrIn gets a reference to the given string and assigns it to the Ipv4AddrIn field.
func (o *OpenVpnRelay) SetIpv4AddrIn(v string) {
	o.Ipv4AddrIn = &v
}

// GetIncludeInCountry returns the IncludeInCountry field value if set, zero value otherwise.
func (o *OpenVpnRelay) GetIncludeInCountry() bool {
	if o == nil || IsNil(o.IncludeInCountry) {
		var ret bool
		return ret
	}
	return *o.IncludeInCountry
}

// GetIncludeInCountryOk returns a tuple with the IncludeInCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenVpnRelay) GetIncludeInCountryOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeInCountry) {
		return nil, false
	}
	return o.IncludeInCountry, true
}

// HasIncludeInCountry returns a boolean if a field has been set.
func (o *OpenVpnRelay) HasIncludeInCountry() bool {
	if o != nil && !IsNil(o.IncludeInCountry) {
		return true
	}

	return false
}

// SetIncludeInCountry gets a reference to the given bool and assigns it to the IncludeInCountry field.
func (o *OpenVpnRelay) SetIncludeInCountry(v bool) {
	o.IncludeInCountry = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *OpenVpnRelay) GetWeight() int32 {
	if o == nil || IsNil(o.Weight) {
		var ret int32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenVpnRelay) GetWeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *OpenVpnRelay) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given int32 and assigns it to the Weight field.
func (o *OpenVpnRelay) SetWeight(v int32) {
	o.Weight = &v
}

func (o OpenVpnRelay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenVpnRelay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Owned) {
		toSerialize["owned"] = o.Owned
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Ipv4AddrIn) {
		toSerialize["ipv4_addr_in"] = o.Ipv4AddrIn
	}
	if !IsNil(o.IncludeInCountry) {
		toSerialize["include_in_country"] = o.IncludeInCountry
	}
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	return toSerialize, nil
}

type NullableOpenVpnRelay struct {
	value *OpenVpnRelay
	isSet bool
}

func (v NullableOpenVpnRelay) Get() *OpenVpnRelay {
	return v.value
}

func (v *NullableOpenVpnRelay) Set(val *OpenVpnRelay) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenVpnRelay) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenVpnRelay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenVpnRelay(val *OpenVpnRelay) *NullableOpenVpnRelay {
	return &NullableOpenVpnRelay{value: val, isSet: true}
}

func (v NullableOpenVpnRelay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenVpnRelay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


