/*
Mullvad App API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mullvad_api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1WireguardKeysPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1WireguardKeysPostRequest{}

// V1WireguardKeysPostRequest struct for V1WireguardKeysPostRequest
type V1WireguardKeysPostRequest struct {
	// The WireGuard public key to add
	Pubkey string `json:"pubkey"`
}

type _V1WireguardKeysPostRequest V1WireguardKeysPostRequest

// NewV1WireguardKeysPostRequest instantiates a new V1WireguardKeysPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1WireguardKeysPostRequest(pubkey string) *V1WireguardKeysPostRequest {
	this := V1WireguardKeysPostRequest{}
	this.Pubkey = pubkey
	return &this
}

// NewV1WireguardKeysPostRequestWithDefaults instantiates a new V1WireguardKeysPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1WireguardKeysPostRequestWithDefaults() *V1WireguardKeysPostRequest {
	this := V1WireguardKeysPostRequest{}
	return &this
}

// GetPubkey returns the Pubkey field value
func (o *V1WireguardKeysPostRequest) GetPubkey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value
// and a boolean to check if the value has been set.
func (o *V1WireguardKeysPostRequest) GetPubkeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pubkey, true
}

// SetPubkey sets field value
func (o *V1WireguardKeysPostRequest) SetPubkey(v string) {
	o.Pubkey = v
}

func (o V1WireguardKeysPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1WireguardKeysPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pubkey"] = o.Pubkey
	return toSerialize, nil
}

func (o *V1WireguardKeysPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pubkey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1WireguardKeysPostRequest := _V1WireguardKeysPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1WireguardKeysPostRequest)

	if err != nil {
		return err
	}

	*o = V1WireguardKeysPostRequest(varV1WireguardKeysPostRequest)

	return err
}

type NullableV1WireguardKeysPostRequest struct {
	value *V1WireguardKeysPostRequest
	isSet bool
}

func (v NullableV1WireguardKeysPostRequest) Get() *V1WireguardKeysPostRequest {
	return v.value
}

func (v *NullableV1WireguardKeysPostRequest) Set(val *V1WireguardKeysPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1WireguardKeysPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1WireguardKeysPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1WireguardKeysPostRequest(val *V1WireguardKeysPostRequest) *NullableV1WireguardKeysPostRequest {
	return &NullableV1WireguardKeysPostRequest{value: val, isSet: true}
}

func (v NullableV1WireguardKeysPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1WireguardKeysPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


