/*
Mullvad App API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mullvad_api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1CreateApplePaymentPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CreateApplePaymentPostRequest{}

// V1CreateApplePaymentPostRequest struct for V1CreateApplePaymentPostRequest
type V1CreateApplePaymentPostRequest struct {
	// An encrypted Base64-encoded App Store receipt
	ReceiptString string `json:"receipt_string"`
}

type _V1CreateApplePaymentPostRequest V1CreateApplePaymentPostRequest

// NewV1CreateApplePaymentPostRequest instantiates a new V1CreateApplePaymentPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CreateApplePaymentPostRequest(receiptString string) *V1CreateApplePaymentPostRequest {
	this := V1CreateApplePaymentPostRequest{}
	this.ReceiptString = receiptString
	return &this
}

// NewV1CreateApplePaymentPostRequestWithDefaults instantiates a new V1CreateApplePaymentPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CreateApplePaymentPostRequestWithDefaults() *V1CreateApplePaymentPostRequest {
	this := V1CreateApplePaymentPostRequest{}
	return &this
}

// GetReceiptString returns the ReceiptString field value
func (o *V1CreateApplePaymentPostRequest) GetReceiptString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReceiptString
}

// GetReceiptStringOk returns a tuple with the ReceiptString field value
// and a boolean to check if the value has been set.
func (o *V1CreateApplePaymentPostRequest) GetReceiptStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceiptString, true
}

// SetReceiptString sets field value
func (o *V1CreateApplePaymentPostRequest) SetReceiptString(v string) {
	o.ReceiptString = v
}

func (o V1CreateApplePaymentPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CreateApplePaymentPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["receipt_string"] = o.ReceiptString
	return toSerialize, nil
}

func (o *V1CreateApplePaymentPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"receipt_string",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1CreateApplePaymentPostRequest := _V1CreateApplePaymentPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1CreateApplePaymentPostRequest)

	if err != nil {
		return err
	}

	*o = V1CreateApplePaymentPostRequest(varV1CreateApplePaymentPostRequest)

	return err
}

type NullableV1CreateApplePaymentPostRequest struct {
	value *V1CreateApplePaymentPostRequest
	isSet bool
}

func (v NullableV1CreateApplePaymentPostRequest) Get() *V1CreateApplePaymentPostRequest {
	return v.value
}

func (v *NullableV1CreateApplePaymentPostRequest) Set(val *V1CreateApplePaymentPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CreateApplePaymentPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CreateApplePaymentPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CreateApplePaymentPostRequest(val *V1CreateApplePaymentPostRequest) *NullableV1CreateApplePaymentPostRequest {
	return &NullableV1CreateApplePaymentPostRequest{value: val, isSet: true}
}

func (v NullableV1CreateApplePaymentPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CreateApplePaymentPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


