/*
Mullvad App API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mullvad_api

import (
	"encoding/json"
)

// checks if the V1RelaysGet200ResponseBridgeShadowsocksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1RelaysGet200ResponseBridgeShadowsocksInner{}

// V1RelaysGet200ResponseBridgeShadowsocksInner struct for V1RelaysGet200ResponseBridgeShadowsocksInner
type V1RelaysGet200ResponseBridgeShadowsocksInner struct {
	Protocol *string `json:"protocol,omitempty"`
	Port *int32 `json:"port,omitempty"`
	Cipher *string `json:"cipher,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewV1RelaysGet200ResponseBridgeShadowsocksInner instantiates a new V1RelaysGet200ResponseBridgeShadowsocksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1RelaysGet200ResponseBridgeShadowsocksInner() *V1RelaysGet200ResponseBridgeShadowsocksInner {
	this := V1RelaysGet200ResponseBridgeShadowsocksInner{}
	return &this
}

// NewV1RelaysGet200ResponseBridgeShadowsocksInnerWithDefaults instantiates a new V1RelaysGet200ResponseBridgeShadowsocksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1RelaysGet200ResponseBridgeShadowsocksInnerWithDefaults() *V1RelaysGet200ResponseBridgeShadowsocksInner {
	this := V1RelaysGet200ResponseBridgeShadowsocksInner{}
	return &this
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) SetProtocol(v string) {
	o.Protocol = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) SetPort(v int32) {
	o.Port = &v
}

// GetCipher returns the Cipher field value if set, zero value otherwise.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) GetCipher() string {
	if o == nil || IsNil(o.Cipher) {
		var ret string
		return ret
	}
	return *o.Cipher
}

// GetCipherOk returns a tuple with the Cipher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) GetCipherOk() (*string, bool) {
	if o == nil || IsNil(o.Cipher) {
		return nil, false
	}
	return o.Cipher, true
}

// HasCipher returns a boolean if a field has been set.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) HasCipher() bool {
	if o != nil && !IsNil(o.Cipher) {
		return true
	}

	return false
}

// SetCipher gets a reference to the given string and assigns it to the Cipher field.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) SetCipher(v string) {
	o.Cipher = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *V1RelaysGet200ResponseBridgeShadowsocksInner) SetPassword(v string) {
	o.Password = &v
}

func (o V1RelaysGet200ResponseBridgeShadowsocksInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1RelaysGet200ResponseBridgeShadowsocksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Cipher) {
		toSerialize["cipher"] = o.Cipher
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableV1RelaysGet200ResponseBridgeShadowsocksInner struct {
	value *V1RelaysGet200ResponseBridgeShadowsocksInner
	isSet bool
}

func (v NullableV1RelaysGet200ResponseBridgeShadowsocksInner) Get() *V1RelaysGet200ResponseBridgeShadowsocksInner {
	return v.value
}

func (v *NullableV1RelaysGet200ResponseBridgeShadowsocksInner) Set(val *V1RelaysGet200ResponseBridgeShadowsocksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1RelaysGet200ResponseBridgeShadowsocksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1RelaysGet200ResponseBridgeShadowsocksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1RelaysGet200ResponseBridgeShadowsocksInner(val *V1RelaysGet200ResponseBridgeShadowsocksInner) *NullableV1RelaysGet200ResponseBridgeShadowsocksInner {
	return &NullableV1RelaysGet200ResponseBridgeShadowsocksInner{value: val, isSet: true}
}

func (v NullableV1RelaysGet200ResponseBridgeShadowsocksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1RelaysGet200ResponseBridgeShadowsocksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


